apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}
  labels:
    {{- include "pi-hole.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pi-hole.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{ end }}