apiVersion: v2
name: ingress-auto-dns
description: A Helm chart designed to rapidly bootstrap an automated internal DNS system for newly created Kubernetes clusters

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: etcd
    version: 11.3.1
    repository: https://charts.bitnami.com/bitnami

  - name: coredns
    version: 1.42.0
    repository: https://coredns.github.io/helm
    
  - name: external-dns
    version: 1.16.1
    repository: https://kubernetes-sigs.github.io/external-dns

  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx
    

    