on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.6.0
      #   with:
      #     charts_dir: charts
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install chart-releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/latest/download/chart-releaser_$(uname -s)_$(uname -m).tar.gz | tar xz
          sudo mv cr /usr/local/bin/cr

      - name: Upload new charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr upload --owner ${{ github.repository_owner }} --git-repo $(basename ${{ github.repository }}) \
            --charts charts --skip-existing

      - name: Update index
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr index --owner ${{ github.repository_owner }} --git-repo $(basename ${{ github.repository }}) \
            --charts charts --push